config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :owners, controllers: {registrations: 'owners/registrations', sessions: 'owners/sessions'}
  # devise が生成してくれたownerモデルのコントローラのうち、registrations_controller はこちらでカスタムしたものを使いますよ、という宣言。（registrationsのすべてのメソッドを定義する必要はなく、カスタムしたいものだけを宣言すればよい）

  resources :owners, only: [:show]
  # showアクションはdeviseにないので、resoucesで用意する。

  resources :users
  # resources :likes, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "users#index"
  get "/users" => "users#index"
  post "/users" => "users#index"
  get "/users/:id" => "users#show"
  post "/users/:id" => "users#show" 
  get "/posts/:id" => "posts#show"
  post "/posts/:id" => "posts#show"
  get "/owners/:id" => "owners#show"
  post "/owners/:id" => "owners#show"

  # いいねのcreate、destroyに使うPOSTメソッド
  post "/likes", to: "likes#create", as: 'likes_create'
  post "/likes/:id", to: "likes#destroy", as: 'likes_destroy'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :owner

  validates :user_id, {presence: true}
  validates :owner_id, {presence: true}
  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :authenticate_owner!

  def create
    @user = User.find(params[:user_id])
    @like = Like.new(owner_id: current_owner.id, user_id: params[:user_id])
    @like.save
    respond_to do |format|
      format.html
      format.js
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @like = Like.find_by(owner_id: current_owner.id, user_id: params[:user_id])
    @like.destroy
    respond_to do |format|
      format.html
      format.js
    end
  end
  
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<%# 自分が飼い主の犬にはいいね出来ないようにする。 %>
<% if signed_in? && user.owner_id != current_owner.id %>
  <% if Like.find_by(owner_id: current_owner.id, user_id: user.id) %>
    <div class="unlike-btn">
      <%= form_tag likes_destroy_path(user_id: user.id, id: @like.id), method: :post, remote: true do %>
        <%= button_tag type: "submit", class: "btn btn-default" do %>
          <i class="fas fa-heart fa-2x"></i>
          <span><%= user.likes.count %> いいね！</span>
        <% end %>
      <% end %>
    </div>
  <% else %>
    <div class="like-btn">
      <%= form_tag likes_create_path(user_id: user.id), method: :post, remote: true do %>
        <%= button_tag type: "submit", class: "btn btn-default" do %>
          <i class="far fa-heart fa-2x"></i>
          <span><%= user.likes.count %> いいね！</span>
        <% end %>
      <% end %>
    </div>
  <% end %>
<% else %>
  <i class="fas fa-heart fa-2x"></i>
  <%= user.likes.count %> いいね！
<% end %>

app/views/likes/create.js.erb
$('.like-buttons').html('<%= j(render partial: '/likes/like', locals: {user: @user}) %>');

app/views/likes/destroy.js.erb
$('.like-buttons').html('<%= j(render partial: '/likes/like', locals: {user: @user}) %>');