config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :owners, controllers: {registrations: 'owners/registrations', sessions: 'owners/sessions'}
  # devise が生成してくれたownerモデルのコントローラのうち、registrations_controller はこちらでカスタムしたものを使いますよ、という宣言。（registrationsのすべてのメソッドを定義する必要はなく、カスタムしたいものだけを宣言すればよい）

  resources :owners, only: [:show]
  # showアクションはdeviseにないので、resoucesで用意する。

  resources :users
  # resources :likes, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "users#index"
  get "/users" => "users#index"
  post "/users" => "users#index"
  get "/users/:id" => "users#show"
  post "/users/:id" => "users#show" 
  get "/posts/:id" => "posts#show"
  post "/posts/:id" => "posts#show"
  get "/owners/:id" => "owners#show"
  post "/owners/:id" => "owners#show"

  # いいねのcreate、destroyに使うPOSTメソッド
  post "/likes", to: "likes#create", as: 'likes_create'
  post "/likes/:id", to: "likes#destroy", as: 'likes_destroy'
end

app/models/user.rb
class User < ApplicationRecord

  belongs_to :owner
  has_many :likes, dependent: :destroy
  has_many :posts, dependent: :destroy

  validates :name, presence: true, length: {maximum: 50}
  validates :age, presence: true
  validates :owner_id, presence: true

  mount_uploader :avatar, AvatarUploader
  # serialize :avatar,JSON unless Rails.env.production?

  def owner
    return Owner.find(self.owner_id)
  end

  def likes
    return Like.where(user_id: self.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_owner!, only: [:new, :create, :edit, :update, :destroy]
  # ログインしていない場合は犬の登録などの操作を制限する。

  before_action :ensure_correct_owner, only: [:edit, :update, :destroy]
  # 飼い主以外は犬の情報を編集できないようにする。

  # GET /users
  # GET /users.json
  def index
    if params[:name] != "" && params[:age] == ""
      @users = User.where('name LIKE ?', "%#{params[:name]}%")
      @users = @users.page(params[:page]).per(10)
      flash[:warning] = "該当データなし" if @users.count == 0
    elsif params[:name] == "" && params[:age] != ""
      @users = User.where(age: params[:age])
      @users = @users.page(params[:page]).per(10)
      flash[:warning] = "該当データなし" if @users.count == 0
    elsif params[:name] && params[:age]
      @users = User.where('name LIKE ?', "%#{params[:name]}%").where(age: params[:age])
      @users = @users.page(params[:page]).per(10)
      flash[:warning] = "該当データなし" if @users.count == 0
    else
      flash[:warning] = ""
      @users = User.page(params[:page]).per(10)
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @like = Like.find_by(owner_id: current_owner.id, user_id: params[:id]) if signed_in?
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.owner_id = current_owner.id

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: '情報を登録しました' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: '情報を更新しました' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: '情報を削除しました' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :age, :avatar, :remove_avatar, :owner_id, :introduction)
    end
    
    # 飼い主以外は犬の情報を編集できないようにするためのメソッド
    def ensure_correct_owner
      @user = User.find(params[:id])
      if current_owner.id != @user.owner_id
        flash[:notice] = "権限がありません"
        redirect_to users_path
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <!--
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
      -->

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li class="alert alert-warning"><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :introduction %>
    <%= form.text_area :introduction, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :avatar %>
    <br>
    <%= form.file_field :avatar %>

  </div>
  <br>
  <% if user.avatar? %>
    <p style="margin: 0;">（現在登録中の写真）</p>
    <%= image_tag user.avatar.url if user.avatar? %>
  <% end %>

  <p>
    <label>
      <%= form.check_box :remove_avatar %>
      写真を削除
    </label>
  </p>

  <br>
  <div class="actions">
    <%= form.submit "登録する", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/_index.html.erb

<%# ページネーション %>
<%= paginate users %>

<%# テーブル %>
<div class="table-narrow table-responsive">
  <table class="table table-striped text-nowrap">
    <thead>
      <tr>
        <th colspan="1"></th>
        <th scope="col"><%= t('activerecord.attributes.user.name') %></th>
        <th scope="col"><%= t('activerecord.attributes.user.age') %></th>
        <th colspan="5"></th>
      </tr>
    </thead>
    <tbody>
      <%= flash[:warning] %>
      <% users.each do |user| %>
        <tr>
          <td><%= image_tag user.avatar.thumb.url if user.avatar? %></td>
          <td><%= user.name %></td>
          <td><%= user.age %></td>
          <td><%= link_to 'プロフィール', user, class: "btn shiney profile" %></td>
          <td><%= link_to '編集', edit_user_path(user), class: "btn shiney edit" if user.owner == current_owner %></td>
          <td><%= link_to '削除', user, method: :delete, data: { confirm: '削除してよろしいですか?' }, class: "btn shiney destroy" if user.owner == current_owner %></td>
          <td>
          <!-- 画像の表示はLityを利用 -->
          <%= link_to '写真を見る', user.avatar.url, 'data-lity': 'data-lity', class: "btn shiney zoom" if user.avatar? %>
        </tr>

      <% end %>
    </tbody>
  </table>

</div>
<%# テーブルここまで %>

<%# ページネーション %>
<%= paginate users %>



app/views/users/edit.html.erb
<div class="box col-md-8 mx-auto">
  <h1>登録情報編集</h1>
  <hr>
  <%= render 'form', user: @user %>

  <hr>

  <%= link_to '更新せずに戻る', @user, class: "btn btn-secondary" %> 

</div>

app/views/users/index.html.erb
<div class="col-md-8 mx-auto">
  <h1>Dogs Information</h1>
</div>

<%# カルーセル %>
<div id="carouselExampleIndicators" class="carousel slide col-md-8 col-xl-6 mx-auto" data-ride="carousel" data-interval="3000" data-pause="false">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="5"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="6"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="7"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="8"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="/dogs/pic_1.jpg" alt="Dogs slide">
    </div>
    <% (2..9).each do |n| %>
      <div class="carousel-item">
        <img class="d-block w-100" src="<%= "/dogs/pic_#{n}.jpg" %>" alt="Dogs slide">
      </div>
    <% end %>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<%# カルーセルここまで %>


<div class="box col-md-12 col-lg-10 col-xl-8 mx-auto">
   
  <h3>あなたの自慢の愛犬をみんなで共有しよう！</h3>
  <p>かわいい愛犬の写真やプロフィールを投稿し、いいね！やコメントをもらいましょう。</p>
  <% unless signed_in? %>
    <p>はじめての方はこちら...
    <%= link_to "ユーザー登録", new_owner_registration_path, class: "btn btn-outline-info" %></p>
  <% end %>
  <br>
  <%# Indexページを呼び出す %>
  <%= render partial: "index", locals: {users: @users} %>
</div>

app/views/users/new.html.erb
<div class="box col-md-12">
  <div class="box col-md-8 mx-auto">
    <h1>愛犬情報を登録</h1>
    <hr>
    <%= render 'form', user: @user %>

    <hr>
    
    <%= link_to '戻る', users_path, class: "btn btn-secondary" %>
  </div>
</div>

app/views/users/show.html.erb
<!--
<ol class="breadcrumb" style="margin-top: -10px;">
  <li class="breadcrumb-item"><a href="#">Home</a></li>
  <li class="breadcrumb-item"><a href="#">Library</a></li>
  <li class="breadcrumb-item active">Data</li>
</ol>
-->

<div class="box col-md-8 mx-auto">
  <h1>愛犬プロフィール</h1>
  <hr>


  <p>
    <strong><%= t 'activerecord.attributes.user.name' %>：</strong>
    <%= @user.name %>
  </p>

  <p>
    <strong><%= t 'activerecord.attributes.user.age' %>：</strong>
    <%= @user.age %>
  </p>

  <p>
    <strong><%= t 'activerecord.attributes.user.owner' %>：</strong>
    <%= @user.owner.name %>
  </p>

  <p>
    <strong><%= t 'activerecord.attributes.user.introduction' %>：</strong>
    <%= @user.introduction %>
  </p>

  <p class="user-show-img">
    <%= image_tag @user.avatar.url if @user.avatar? %>
  </p>

  <p>（最終更新：<%= @user.updated_at.strftime('%Y年%m月%d日') %>）</p> 

  <%# いいねボタンを表示 %>
  <div class="like-buttons">
    <%= render partial: '/likes/like',locals: {user: @user} %>
  </div>

  <% unless signed_in? %>
    <p class="border-info">「いいね！」やコメントをするには、ログインが必要です。</p>
  <% end %>

  <hr>
  <% if @user.owner == current_owner %>
    <%= link_to '情報編集', edit_user_path(@user), class: "btn btn-primary btn-info" %> 
  <% end %>

  <%# ログインしている場合だけ、返信ボタンを有効化 %>
  <% if signed_in? %>
    <%= form_tag(new_post_path, method: "get",class: "form-inline-block") do %>
      
      <%= submit_tag "コメントする", class: "btn btn-primary" %>
      <%= hidden_field_tag :user_id, @user.id %>
      <%= 
        if current_owner 
          hidden_field_tag :owner_id, current_owner.id
        else
          ""
        end
      %>
    <% end %>
  <% else %>
    <button type="button" class="btn btn-primary" disabled>コメントする</button>
  <% end %>
  
  <%= link_to '戻る', users_path, class: "btn btn-secondary" %>

  <!-- コメント一覧 -->
  <hr>
  <h3>コメント</h3>
  <% Post.all.each do |post| %>
    <% if @user.id == post.user_id %>
      <p>
        <% if @user.owner_id == post.owner_id %>
          <b><%= post.owner.name %> - <%= post.created_at.strftime('%Y年%m月%d日') %>（飼い主さんのコメント）</b>
        <% else %>
          <b><%= post.owner.name %> - <%= post.created_at.strftime('%Y年%m月%d日') %></b>
        <% end %>
        <%= simple_format post.content %>
      </p>
    <% end %>
  <% end %>
</div>

app/views/users/show.js.erb
$('h1').html("<i class='fas fa-lemon'></i>");