config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :owners, controllers: {registrations: 'owners/registrations', sessions: 'owners/sessions'}
  # devise が生成してくれたownerモデルのコントローラのうち、registrations_controller はこちらでカスタムしたものを使いますよ、という宣言。（registrationsのすべてのメソッドを定義する必要はなく、カスタムしたいものだけを宣言すればよい）

  resources :owners, only: [:show]
  # showアクションはdeviseにないので、resoucesで用意する。

  resources :users
  # resources :likes, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "users#index"
  get "/users" => "users#index"
  post "/users" => "users#index"
  get "/users/:id" => "users#show"
  post "/users/:id" => "users#show" 
  get "/posts/:id" => "posts#show"
  post "/posts/:id" => "posts#show"
  get "/owners/:id" => "owners#show"
  post "/owners/:id" => "owners#show"

  # いいねのcreate、destroyに使うPOSTメソッド
  post "/likes", to: "likes#create", as: 'likes_create'
  post "/likes/:id", to: "likes#destroy", as: 'likes_destroy'
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="header">
  <%= link_to "Dogs", users_path, class: "navbar-brand" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse shift" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to root_path, class: "nav-link" do %>
          ホーム <span class="sr-only">(current)</span>
        <% end %>
      </li>
      <% if signed_in? %>
        <li class="nav-item">
          <%= link_to "愛犬登録", new_user_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "ユーザー情報", current_owner, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "ログアウト", destroy_owner_session_path, method: 'delete', class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%# ログインフォームをモーダル化 %>
          <%= link_to "ログイン", '', class: "nav-link", "data-toggle": "modal", "data-target": "#signinModal" %>
        </li>
        <li class="nav-item">
          <%= link_to "ユーザー登録", new_owner_registration_path, class: "nav-link" %>
        </li>
        &ensp;
      <% end %>
    </ul>
    <%= form_tag(users_path, method: "get", class: "form-inline my-2 my-lg-0") do %>
    <%# 検索する場合は必ず method: "get" にする。get意外だと脆弱性が発生する。参考↓ %>
    <%# https://railsguides.jp/form_helpers.html %>
      <%= text_field_tag :name, '', class: "form-control mr-sm-2", placeholder: "犬の名前で検索" %>
      
      <!-- Userモデルのageカラムを取り出し、重複を除く -->
      <% age_distinct = [] %>
      <% User.select("age").distinct.each do |a|  %>
        <% age_distinct << [a.age, a.age] %>
      <% end %>

      <%= select_tag :age, options_for_select(age_distinct, selected: params[:age]), class: "form-control", prompt: "年齢で検索..." %>
      &ensp;
      <%= submit_tag '検索', class: "btn btn-outline-success my-2 my-sm-0 slide" %>
    <% end %>
  </div>
</nav>

<%# ログインフォームモーダル %>
<%= render partial: '/devise/sessions/new' %>

app/views/layouts/_modal.html.erb
<% @users.each do |user| %>
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" style="margin: 200px auto; height: 700px;">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel"><%= user.name %></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= image_tag user.avatar.url if user.avatar? %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <title>Dogs information</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <!-- jquery 
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>-->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Lity -->
    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/lity/1.6.6/lity.js'></script>
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/lity/1.6.6/lity.css' />  

    <%# Bootstrap ver.4 %>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.bundle.min.js" integrity="sha384-pjaaA8dDz/5BgdFUPX6M/9SUZv4d12SUPF0axWc+VRZkx5xU3daN+lYb49+Ax+Tl" crossorigin="anonymous"></script>
    
    <!-- fontawesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

    <%# CSS %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%# フォント %>
    <link href="https://fonts.googleapis.com/css?family=Kosugi+Maru|Varela+Round" rel="stylesheet">
  </head>

  <body>
    <!-- As a link -->
    <%# ナビゲーションバー %>
    <header>
      <%= render partial: '/layouts/header' %> 
    </header>
    
    <div class="containerfluid">
      <div class="row">
        <div class="box col-md-12 mx-auto">

          <%# flashメッセージを表示 %>
          <!-- <%= devise_error_messages! %> -->

          <% flash.each do |key, value| %>
            <% if flash[key] != "" %>
              <div class="alert <%= bootstrap_class_for(key) %>">
                <%= value %>
              </div>
            <% end %>
          <% end %>

          <%# ここにほかのビューが挿入される %>
          <%= yield %>
        
          <%# デバッグ %>
          <%= debug params if Rails.env.development? %> 
        </div>
      </div>
    </div>
      
  </body>
</html>